### ISSUE TITLE
被卡巴斯基当成木马强制中止并且删除了

### ISSUE THREAD

**Issue by Asvolt** [infrost/ColDataRefresh#1]
现在主要是有点担心会不会有数据损坏

**Comment by infrost** [comment]
您好，关于杀毒软件报毒的事情，是因为这个的`.exe`文件是使用nuitka打包编译的单文件python程序，程序运行的时候会自己向系统的缓存目录展开依赖，由于还有读写非运行目录的操作，这和一些病毒的行为有些相似，所以会误报，这是正常现象，也是在项目说明中`推荐直接从python源代码运行`的原因。


------------------------------------

关于程序在运行时被强制终止并删除，是否会造成数据损坏，我不敢打包票说数据100%不会损坏。我可以告诉您的是，**程序在设计的时候就将数据安全放在很高的优先级。**

代码逻辑是先把文件复制到缓存目录，然后校验缓存目录的文件是否和原文件crc值一致，如果一致则将缓存目录的文件“移动”至原同名文件目录下（即“替换”）。在ntfs文件系统里，移动这个操作并不会实际移动数据块，只是改变MFT表文件指向，因此速度很快且通常是原子操作（您可以理解为这个“替换文件”操作只有执行成功和失败两种可能，而无论是否成功替换，源文件的数据都是完整的）。**因此，理论上，在您描述的case里的中断程序的情况，是不会造成文件数据损坏的。**

**Comment by Asvolt** [comment]
> 您好，关于杀毒软件报毒的事情，是因为这个的`.exe`文件是使用nuitka打包编译的单文件python程序，程序运行的时候会自己向系统的缓存目录展开依赖，由于还有读写非运行目录的操作，这和一些病毒的行为有些相似，所以会误报，这是正常现象，也是在项目说明中`推荐直接从python源代码运行`的原因。
> 
> 关于程序在运行时被强制终止并删除，是否会造成数据损坏，我不敢打包票说数据100%不会损坏。我可以告诉您的是，**程序在设计的时候就将数据安全放在很高的优先级。**
> 
> 代码逻辑是先把文件复制到缓存目录，然后校验缓存目录的文件是否和原文件crc值一致，如果一致则将缓存目录的文件“移动”至原同名文件目录下（即“替换”）。在ntfs文件系统里，移动这个操作并不会实际移动数据块，只是改变MFT表文件指向，因此速度很快且通常是原子操作（您可以理解为这个“替换文件”操作只有执行成功和失败两种可能，而无论是否成功替换，源文件的数据都是完整的）。**因此，理论上，在您描述的case里的中断程序的情况，是不会造成文件数据损坏的。**

感谢解答
